### ISSUE TITLE
ADD Player Controls buttons (← +xxxx ms →) for audio delay adjustment

### ISSUE THREAD

**Issue by allanlaal** [adrian-ilie/av-sync#1]
## use case:

need to constantly adjust audio delay

## expected

something like this:

![controls](https://user-images.githubusercontent.com/740826/83765140-7dd10b80-a683-11ea-972a-49f57d963aa9.png)

both with normal player and fullscreen player
if control buttons are images, then circles around them too plz =)

if audio sync is disabled, then grey everything out. do not hide controls, even if disabled or 0ms)

click on xxx ms value will reset it back to 0. another click will restore the previous value

sync direction is shown with: +1337ms or -1337ms

**Comment by allanlaal** [comment]
would include a checkbox or some sort of clear icons for #5 (opens on hovering on value or is always visible)

**Comment by adrian-ilie** [comment]
Thank you for the suggestions!

In addition to the control buttons I am thinking to also make it possible to edit the value in milliseconds directly.

"click on xxx ms value will reset it back to 0. another click will restore the previous value"
This is already covered by clicking on the extension's icon, I would rather use the click action inside the player for editing.

**Comment by adrian-ilie** [comment]
Fixed in v0.0.9 except for graying everything out, for people who only set the delay once and then only use the extension icon to enable/disable, they don't need to see the grey out controls in every video. I might consider adding it in a future release if it makes sense for most users.

You can edit the value in ms now the player (through the +/- buttons or just writing the value). 
I've also added an option to hide the player controls from the options page.
