### ISSUE TITLE
issue when I disable player control

### ISSUE THREAD

**Issue by smenes** [adrian-ilie/av-sync#6]
Hi
thanks for this helpful extension.
The audio delay with my bluetooth headphones (Sony wh-1000xm4) is always the same (170ms).
So I don't need player control for the adjustment.

but if i uncheck the option, when i start a video it is fine, but if i go forward in the video, the sound does not move forward so it gets out of sync.

extension version 0.1.9
on Chromium version 88.0.4324.182 (Build officiel) Arch Linux (64 bits)

**Comment by adrian-ilie** [comment]
Hi,

In v0.2.0 I've moved the controls to a new menu (it can be accessed by clicking on the button next to the settings in the player). I've also removed the possibility to hide the controls since it is not needed anymore. 
However I am not sure if this has solved your problem (as it shouldn't have caused it in the first place) so please let me know if v0.2.0 works good for you.

**Comment by smenes** [comment]
thank you it works
it's better like this, thanks
